begin;
CREATE USER api_user WITH PASSWORD 'jhpiowuhp10';
CREATE SCHEMA "score_db";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS citext;

GRANT ALL PRIVILEGES ON DATABASE "score_db" to api_user;
GRANT ALL PRIVILEGES ON SCHEMA score_db TO api_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA score_db TO api_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA score_db TO api_user;
end;